name: Build Ubuntu App

on:
  push:
    branches:
      - main     # Kích hoạt khi push code lên nhánh main
    tags:
      - 'v*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Lấy code từ kho lưu trữ về máy ảo Ubuntu
    - name: Checkout Code
      uses: actions/checkout@v4

    # Bước 2: Thiết lập Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Bước 3: Cài đặt các thư viện Python cần thiết
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywebview pyinstaller pypdf youtube-transcript-api deep-translator

    # Bước 4: Đóng gói ứng dụng bằng PyInstaller (Sử dụng dấu : chuẩn Linux và bỏ --icon do Linux không hỗ trợ nhúng icon vào binary)
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-data "templates:templates" app.py

    # Bước 5: Tự động tạo Release và đẩy file chạy Linux lên khi tạo tags (Ví dụ: v1.0.0)
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') # Chỉ chạy bước này khi bạn push tag dạng v*
      with:
        files: dist/app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}